version: "3"

networks:
  web:
    external: true 

services:
  traefik:
    image: traefik:v2.2 
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml
      - ./acme.json:/acme.json
    networks:
      - web

