[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$EF.Cf/su$l4SiVTH.D5o58OIrY0wvn."
  ]

[http.routers.api]
  rule = "Host(`traefik.manseau.dev`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

